### ISSUE TITLE
I see HTML in the date, what am I missing?

### ISSUE THREAD

**Issue by ninjaslikecheese** [ramnes/qtile-config#2]
First thanks for sharing the config, it's awesome and clean. 
It's more of a question than an actual issue. I'm kind of new to Qtile and it seems Clock() doesn't parse the <span> tags correctly, so I see them there. Am I missing anything? 
Thanks a lot!

**Comment by ninjaslikecheese** [comment]
I figured it out:
```
        Clock(fmt=" ⏱ %H:%M  <span color='#666'>{}</span>  ", format="%A %d-%m-%Y")
```
It might be that I'm using version 0.12 instead of the latest, though.

**Comment by ramnes** [comment]
Hey @ninjaslikecheese, thanks for the kind words!

The "HTML" you see is actually some Pango markup. If it's not rendered correctly, it's probably because you're not running on Qtile's HEAD, because I pushed [a commit on Qtile](https://github.com/qtile/qtile/commit/dd0ae55847564f248f7c8d1245d46bb03fc6f2a5) a few days ago to activate the Pango markup rendering on all text widgets by default.

You can either update Qtile or downgrade my configuration to 5387044de1c737cccaf1f3680e75076785e4a959, that should work with the 0.14.2 release.

Don't hesitate if you need anything more!
